<template><div><h1 id="enemyfactory" tabindex="-1"><a class="header-anchor" href="#enemyfactory"><span>EnemyFactory</span></a></h1>
<p>La clase <code v-pre>EnemyFactory</code> es una clase que se encarga de crear enemigos de forma dinámica. Esta clase es muy útil cuando
necesitas crear enemigos de forma dinámica en tu juego.</p>
<h2 id="creando-un-enemigo" tabindex="-1"><a class="header-anchor" href="#creando-un-enemigo"><span>Creando un enemigo</span></a></h2>
<p>Para crear un enemigo, simplemente debes llamar al método <code v-pre>generateRegularEnemy</code> de la clase <code v-pre>EnemyFactory</code>. Este método
no recibe ningún parámetro y devuelve un enemigo de tipo <code v-pre>RegularEnemy</code>.</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code>    <span class="token keyword">package</span> <span class="token namespace">util<span class="token punctuation">.</span>enemies</span><span class="token punctuation">;</span>
    
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">enemies<span class="token punctuation">.</span></span><span class="token class-name">Enemy</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">enemies<span class="token punctuation">.</span>bats<span class="token punctuation">.</span></span><span class="token class-name">TinyBat</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">gui<span class="token punctuation">.</span>panels<span class="token punctuation">.</span></span><span class="token class-name">DialogPanel</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>reflections<span class="token punctuation">.</span></span><span class="token class-name">Reflections</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>reflections<span class="token punctuation">.</span>scanners<span class="token punctuation">.</span></span><span class="token class-name">SubTypesScanner</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>reflections<span class="token punctuation">.</span>scanners<span class="token punctuation">.</span></span><span class="token class-name">TypeAnnotationsScanner</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>reflections<span class="token punctuation">.</span>util<span class="token punctuation">.</span></span><span class="token class-name">ClasspathHelper</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>reflections<span class="token punctuation">.</span>util<span class="token punctuation">.</span></span><span class="token class-name">ConfigurationBuilder</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">player<span class="token punctuation">.</span></span><span class="token class-name">Player</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">util<span class="token punctuation">.</span>annotations<span class="token punctuation">.</span></span><span class="token class-name">RegularEnemy</span></span><span class="token punctuation">;</span>
    
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>util<span class="token punctuation">.</span></span><span class="token class-name">ArrayList</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>util<span class="token punctuation">.</span></span><span class="token class-name">List</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>util<span class="token punctuation">.</span></span><span class="token class-name">Random</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>util<span class="token punctuation">.</span></span><span class="token class-name">Set</span></span><span class="token punctuation">;</span>
    
    <span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">EnemyFactory</span> <span class="token punctuation">{</span>
    
        <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token class-name">Random</span> random <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Random</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    
        <span class="token doc-comment comment">/**
         * Genera un enemigo regular aleatorio
         *
         * <span class="token keyword">@return</span> un enemigo regular
         */</span>
        <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">Enemy</span> <span class="token function">generateRegularEnemy</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
            <span class="token class-name">Player</span> player <span class="token operator">=</span> <span class="token class-name">Player</span><span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// Reflections es una librería que permite obtener información sobre las clases de un paquete</span>
            <span class="token class-name">Reflections</span> reflections <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Reflections</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">ConfigurationBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                    <span class="token punctuation">.</span><span class="token function">setUrls</span><span class="token punctuation">(</span><span class="token class-name">ClasspathHelper</span><span class="token punctuation">.</span><span class="token function">forJavaClassPath</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
                    <span class="token punctuation">.</span><span class="token function">setScanners</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">SubTypesScanner</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">TypeAnnotationsScanner</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// Obtiene todas las clases que tienen la anotación RegularEnemy</span>
            <span class="token class-name">Set</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Class</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> classes <span class="token operator">=</span> reflections<span class="token punctuation">.</span><span class="token function">getTypesAnnotatedWith</span><span class="token punctuation">(</span><span class="token class-name">RegularEnemy</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// Convierte el conjunto de clases a una lista</span>
            <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Class</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> classList <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>classes<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// Obtiene una clase aleatoria de la lista</span>
            <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> claseEnemyRegular <span class="token operator">=</span> classList<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>random<span class="token punctuation">.</span><span class="token function">nextInt</span><span class="token punctuation">(</span>classList<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// Intenta crear una instancia de la clase obtenida</span>
            <span class="token keyword">try</span> <span class="token punctuation">{</span>
    
                <span class="token class-name">Enemy</span> enemy <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token class-name">Enemy</span><span class="token punctuation">)</span> claseEnemyRegular<span class="token punctuation">.</span><span class="token function">getDeclaredConstructor</span><span class="token punctuation">(</span><span class="token class-name">Player</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">newInstance</span><span class="token punctuation">(</span>player<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token class-name">DialogPanel</span><span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">addText</span><span class="token punctuation">(</span><span class="token string">"¡Un "</span> <span class="token operator">+</span> enemy<span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">" aparece frente a ti!\n"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">return</span> enemy<span class="token punctuation">;</span>
            <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">Exception</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
                <span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">TinyBat</span><span class="token punctuation">(</span>player<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>En el código anterior, se muestra cómo se puede crear un enemigo de forma dinámica. La clase <code v-pre>EnemyFactory</code> tiene un
método llamado <code v-pre>generateRegularEnemy</code> que se encarga de crear un enemigo de forma dinámica. Este método utiliza la
librería Reflections para obtener todas las clases que tienen la anotación <code v-pre>RegularEnemy</code>. Luego, selecciona una clase
aleatoria de la lista y crea una instancia de esa clase.</p>
<h2 id="anotacion-regularenemy" tabindex="-1"><a class="header-anchor" href="#anotacion-regularenemy"><span>Anotación RegularEnemy</span></a></h2>
<p>Para que una clase pueda ser seleccionada por la clase <code v-pre>EnemyFactory</code>, debe tener la anotación <code v-pre>RegularEnemy</code>. Esta
anotación no tiene ningún atributo y se utiliza simplemente para marcar las clases que pueden ser seleccionadas por la
clase <code v-pre>EnemyFactory</code>.</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code>    <span class="token keyword">package</span> <span class="token namespace">util<span class="token punctuation">.</span>annotations</span><span class="token punctuation">;</span>
    
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">java<span class="token punctuation">.</span>lang<span class="token punctuation">.</span>annotation<span class="token punctuation">.</span></span><span class="token operator">*</span></span><span class="token punctuation">;</span>
    
    <span class="token annotation punctuation">@Target</span><span class="token punctuation">(</span><span class="token class-name">ElementType</span><span class="token punctuation">.</span><span class="token constant">TYPE</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@Retention</span><span class="token punctuation">(</span><span class="token class-name">RetentionPolicy</span><span class="token punctuation">.</span><span class="token constant">RUNTIME</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token annotation punctuation">@interface</span> <span class="token class-name">RegularEnemy</span> <span class="token punctuation">{</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>En el código anterior, se muestra cómo se puede crear una anotación llamada <code v-pre>RegularEnemy</code>. Esta anotación se utiliza
para marcar las clases que pueden ser seleccionadas por la clase <code v-pre>EnemyFactory</code>.</p>
<h2 id="creando-una-clase-de-enemigo" tabindex="-1"><a class="header-anchor" href="#creando-una-clase-de-enemigo"><span>Creando una clase de enemigo</span></a></h2>
<p>Para crear una clase de enemigo que pueda ser seleccionada por la clase <code v-pre>EnemyFactory</code>, simplemente debes añadir la
anotación <code v-pre>RegularEnemy</code> a la clase. Por ejemplo, la clase <code v-pre>TinyBat</code> es una clase de enemigo que tiene la anotación
<code v-pre>RegularEnemy</code>.</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code>    <span class="token keyword">package</span> <span class="token namespace">enemies<span class="token punctuation">.</span>bats</span><span class="token punctuation">;</span>
    
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">enemies<span class="token punctuation">.</span></span><span class="token class-name">Enemy</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">gui<span class="token punctuation">.</span>exceptions<span class="token punctuation">.</span></span><span class="token class-name">EnemyDeadException</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">items<span class="token punctuation">.</span>misc<span class="token punctuation">.</span></span><span class="token class-name">BatEar</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">items<span class="token punctuation">.</span>misc<span class="token punctuation">.</span></span><span class="token class-name">BatWing</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">player<span class="token punctuation">.</span></span><span class="token class-name">Player</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">player<span class="token punctuation">.</span></span><span class="token class-name">Stats</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">util<span class="token punctuation">.</span>annotations<span class="token punctuation">.</span></span><span class="token class-name">RegularEnemy</span></span><span class="token punctuation">;</span>
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">util<span class="token punctuation">.</span>interfaces<span class="token punctuation">.</span></span><span class="token class-name">Randomized</span></span><span class="token punctuation">;</span>
    
    <span class="token keyword">import</span> <span class="token import"><span class="token namespace">javax<span class="token punctuation">.</span>swing<span class="token punctuation">.</span></span><span class="token operator">*</span></span><span class="token punctuation">;</span>
    
    <span class="token annotation punctuation">@RegularEnemy</span>
    <span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">TinyBat</span> <span class="token keyword">extends</span> <span class="token class-name">Enemy</span> <span class="token punctuation">{</span>
    
        <span class="token keyword">public</span> <span class="token class-name">TinyBat</span><span class="token punctuation">(</span><span class="token class-name">Player</span> player<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
            <span class="token keyword">super</span><span class="token punctuation">(</span>player<span class="token punctuation">,</span> <span class="token string">"Mur. Diminuto"</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            image <span class="token operator">=</span> imageManager<span class="token punctuation">.</span><span class="token function">getImage</span><span class="token punctuation">(</span><span class="token string">"tinyBat"</span><span class="token punctuation">,</span>
                    <span class="token keyword">new</span> <span class="token class-name">ImageIcon</span><span class="token punctuation">(</span><span class="token string">"img\\enemies\\bats\\tinyBat.png"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getImage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            stats<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span><span class="token class-name">Stats</span><span class="token punctuation">.</span><span class="token constant">ATTACK</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            stats<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span><span class="token class-name">Stats</span><span class="token punctuation">.</span><span class="token constant">DEFENSE</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            stats<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span><span class="token class-name">Stats</span><span class="token punctuation">.</span><span class="token constant">LUCK</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            stats<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span><span class="token class-name">Stats</span><span class="token punctuation">.</span><span class="token constant">SPEED</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            stats<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span><span class="token class-name">Stats</span><span class="token punctuation">.</span><span class="token constant">DEXTERITY</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    
    
        <span class="token annotation punctuation">@Override</span>
        <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getAttack</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">throws</span> <span class="token class-name">EnemyDeadException</span> <span class="token punctuation">{</span>
    
            <span class="token class-name">Player</span> player <span class="token operator">=</span> <span class="token class-name">Player</span><span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> message <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token function">isDead</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
                <span class="token keyword">double</span> simpleAttackProbability <span class="token operator">=</span> <span class="token number">0.5</span><span class="token punctuation">;</span>
                <span class="token keyword">double</span> screechProbability <span class="token operator">=</span> <span class="token number">0.5</span><span class="token punctuation">;</span>
                <span class="token keyword">double</span> totalProbability <span class="token operator">=</span> simpleAttackProbability <span class="token operator">+</span> screechProbability<span class="token punctuation">;</span>
                <span class="token keyword">double</span> ratio <span class="token operator">=</span> <span class="token class-name">Randomized</span><span class="token punctuation">.</span><span class="token function">randomizeDouble</span><span class="token punctuation">(</span>totalProbability<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token comment">// simpleAttackProbability = 50%, screechProbability = 50%</span>
                <span class="token comment">// simpleAttackProbability + screechProbability = 100%</span>
                <span class="token comment">// ratio = 0.0 - 0.5 -> simpleAttack, ratio = 0.51 - 1.0 -> screech</span>
                <span class="token keyword">if</span> <span class="token punctuation">(</span>ratio <span class="token operator">&lt;=</span> simpleAttackProbability<span class="token punctuation">)</span> message <span class="token operator">=</span> <span class="token function">simpleAttack</span><span class="token punctuation">(</span>player<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">else</span> message <span class="token operator">=</span> <span class="token function">screech</span><span class="token punctuation">(</span>player<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">EnemyDeadException</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">return</span> message<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    
        <span class="token annotation punctuation">@Override</span>
        <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">dropItem</span><span class="token punctuation">(</span><span class="token class-name">Player</span> player<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
            <span class="token keyword">int</span> ratio <span class="token operator">=</span> <span class="token class-name">Randomized</span><span class="token punctuation">.</span><span class="token function">randomizeNumber</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            player<span class="token punctuation">.</span><span class="token function">getInventory</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">addItem</span><span class="token punctuation">(</span>ratio <span class="token operator">></span> <span class="token number">50</span> <span class="token operator">?</span> <span class="token keyword">new</span> <span class="token class-name">BatWing</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">BatEar</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    
        <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">simpleAttack</span><span class="token punctuation">(</span><span class="token class-name">Player</span> player<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
            <span class="token keyword">int</span> damage <span class="token operator">=</span> <span class="token function">getDamage</span><span class="token punctuation">(</span>player<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> message <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span><span class="token string">"¡%s ataca con %d punto(s) de daño!\n"</span><span class="token punctuation">,</span> <span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> damage<span class="token punctuation">)</span><span class="token punctuation">;</span>
            message <span class="token operator">+=</span> player<span class="token punctuation">.</span><span class="token function">takeDamage</span><span class="token punctuation">(</span>damage<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">return</span> message<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    
        <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">screech</span><span class="token punctuation">(</span><span class="token class-name">Player</span> player<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    
            <span class="token keyword">int</span> damage <span class="token operator">=</span> <span class="token function">getAdjustedAttack</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token number">3</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> message <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span><span class="token string">"¡%s emite un chillido ensordecedor que causa %d punto(s) de daño!\n"</span><span class="token punctuation">,</span> <span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
                    damage<span class="token punctuation">)</span><span class="token punctuation">;</span>
            message <span class="token operator">+=</span> player<span class="token punctuation">.</span><span class="token function">takeDamage</span><span class="token punctuation">(</span>damage<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">return</span> message<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>En el código anterior, se muestra cómo se puede crear una clase de enemigo que puede ser seleccionada por la clase
<code v-pre>EnemyFactory</code>. La clase <code v-pre>TinyBat</code> tiene la anotación <code v-pre>RegularEnemy</code>, lo que significa que puede ser seleccionada por la
clase <code v-pre>EnemyFactory</code>.</p>
<h2 id="conclusion" tabindex="-1"><a class="header-anchor" href="#conclusion"><span>Conclusión</span></a></h2>
<p>La clase <code v-pre>EnemyFactory</code> es una clase muy útil cuando necesitas crear enemigos de forma dinámica en tu juego. Esta clase
te permite crear enemigos de forma aleatoria y añadir variedad a tu juego. Además, la anotación <code v-pre>RegularEnemy</code> te
permite marcar las clases que pueden ser seleccionadas por la clase <code v-pre>EnemyFactory</code>. En resumen, la clase <code v-pre>EnemyFactory</code>
es una herramienta muy útil para crear enemigos de forma dinámica en tu juego.</p>
</div></template>


