<template><div><h2 id="version-1-2-0-del-arbol-de-paquetes" tabindex="-1"><a class="header-anchor" href="#version-1-2-0-del-arbol-de-paquetes"><span>Version 1.2.0 del árbol de paquetes <Badge text="Nuevo" type="tip" vertical="middle" /></span></a></h2>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>📦 JavaRPG
└─ src
   ├─ Main.java
   ├─ characters
   │  └─ BasicCharacter.java
   ├─ enemies
   │  ├─ Enemy.java
   │  └─ goblins
   │     └─ RookieGoblin.java
   ├─ item
   │  ├─ Item.java
   │  ├─ armors
   │  │  ├─ Armor.java
   │  │  └─ helmet
   │  │     ├─ IronHelmet.java
   │  │     └─ WoodHelmet.java
   │  └─ weapon
   │     ├─ Weapon.java
   │     └─ WeaponType.java
   ├─ player
   │  ├─ Inventory.java
   │  └─ Player.java
   └─ util
      ├─ FixedArrayList.java
      └─ Randomized.java
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>©generated by <a href="https://woochanleee.github.io/project-tree-generator" target="_blank" rel="noopener noreferrer">Project Tree Generator<ExternalLinkIcon/></a></p>
</div></template>


