name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/checkout@v4
      with:
        # fetch all commits to get last updated time or other git log info
        fetch-depth: 0

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        # choose pnpm version to use
        version: 8
        # install deps with pnpm
        run_install: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        # choose node.js version to use
        node-version: 20
        # cache deps for pnpm
        cache: pnpm

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: jesus-castro89/rpg_java
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: blog/.vuepress/dist/
