name: Deploy to GitHub pages
on:
 push:
    branches: [ main ]
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Build VuePress site
      run: yarn build

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Copy files to gh-pages branch
      run: cp -R .vuepress/dist/* .

    - name: Commit and push to gh-pages
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push
